sevsnp-vmsa-r1-55 = &(
  ? &(page-data: -2) => byte .bits sev-snp-page-data
  ? &(vmpl-perms: -1) => uint .size 8
  ? &(es: 0) => svm-vmcb-seg-map
  ? &(cs: 1) => svm-vmcb-seg-map
  ? &(ss: 2) => svm-vmcb-seg-map
  ? &(ds: 3) => svm-vmcb-seg-map
  ? &(fs: 4) => svm-vmcb-seg-map
  ? &(gs: 5) => svm-vmcb-seg-map
  ? &(ldtr: 6) => svm-vmcb-seg-map
  ? &(gdtr: 7) => svm-vmcb-seg-map
  ? &(idtr: 8) => svm-vmcb-seg-map
  ? &(tr: 9) => svm-vmcb-seg-map
  ? &(pl0_ssp: 10) => uint64
  ? &(pl1_ssp: 11) => uint64
  ? &(pl2_ssp: 12) => uint64
  ? &(pl3_ssp: 13) => uint64
  ? &(u_cet: 14) => uint64
  ? &(vmpl: 15) => byte
  ? &(cpl: 16) => byte
  ? &(efer: 17) => uint64
  ? &(perf_ctl0: 18) => uint64
  ? &(perf_ctr0: 19) => uint64
  ? &(perf_ctl1: 20) => uint64
  ? &(perf_ctr1: 21) => uint64
  ? &(perf_ctl2: 22) => uint64
  ? &(perf_ctr2: 23) => uint64
  ? &(perf_ctl3: 24) => uint64
  ? &(perf_ctr3: 25) => uint64
  ? &(perf_ctl4: 26) => uint64
  ? &(perf_ctr4: 27) => uint64
  ? &(perf_ctl5: 28) => uint64
  ? &(perf_ctr5: 29) => uint64
  ? &(xss: 30) => uint64
  ? &(cr4: 31) => uint64
  ? &(cr3: 32) => uint64
  ? &(cr0: 33) => uint64
  ? &(dr7: 34) => uint64
  ? &(dr6: 35) => uint64
  ? &(rflags: 36) => uint64
  ? &(rip: 37) => uint64
  ? &(dr0: 38) => uint64
  ? &(dr1: 39) => uint64
  ? &(dr2: 40) => uint64
  ? &(dr3: 41) => uint64
  ? &(dr0_addr_mask: 42) => uint64
  ? &(dr1_addr_mask: 43) => uint64
  ? &(dr2_addr_mask: 44) => uint64
  ? &(dr3_addr_mask: 45) => uint64
  ? &(instr_retired_ctr: 46) => uint64
  ? &(perf_ctr_global_sts: 47) => uint64
  ? &(perf_ctr_global_ctl: 48) => uint64
  ? &(rsp: 49) => uint64
  ? &(s_cet: 50) => uint64
  ? &(ssp: 51) => uint64
  ? &(isst_addr: 52) => uint64
  ? &(rax: 53) => uint64
  ? &(star: 54) => uint64
  ? &(lstar: 55) => uint64
  ? &(cstar: 56) => uint64
  ? &(sfmask: 57) => uint64
  ? &(kernel_gs_base: 58) => uint64
  ? &(sysenter_cs: 59) => uint64
  ? &(sysenter_esp: 60) => uint64
  ? &(sysenter_eip: 61) => uint64
  ? &(cr2: 62) => uint64
  ? &(g_pat: 63) => uint64
  ? &(dbgctl: 64) => uint64
  ? &(br_from: 65) => uint64
  ? &(br_to: 66) => uint64
  ? &(last_excp_from: 67) => uint64
  ? &(last_excp_to: 68) => uint64
  ? &(dbgextngfg: 69) => uint64
  ? &(spec_ctrl: 70) => uint64
  ? &(pkru: 71) => uint64
  ? &(tsc_aux: 72) => uint64
  ? &(guest_tsc_scale: 73) => uint64
  ? &(guest_tsc_offset: 74) => uint64
  ? &(reg_prot_nonce: 75) => uint64
  ? &(rcx: 76) => uint64
  ? &(rdx: 77) => uint64
  ? &(rbx: 78) => uint64
  ? &(secure_avic_ctl: 79) => uint64
  ? &(rbp: 80) => uint64
  ? &(rsi: 81) => uint64
  ? &(rdi: 82) => uint64
  ? &(r8: 83) => uint64
  ? &(r9: 84) => uint64
  ? &(r10: 85) => uint64
  ? &(r11: 86) => uint64
  ? &(r12: 87) => uint64
  ? &(r13: 88) => uint64
  ? &(r14: 89) => uint64
  ? &(r15: 90) => uint64
  ? &(sev_features: 91) => uint64
  ? &(vintr_ctrl: 92) => uint64
  ? &(virtual_tom: 93) => uint64
  ? &(tlb_id: 94) => uint64
  ? &(pcpu_id: 95) => uint64
  ? &(event_inj: 96) => uint64
  ? &(xcr0: 97) => uint64
  ? &(x87_dp: 98) => uint64
  ? &(mxcsr: 99) => uint32
  ? &(x87_ftw: 100) => uint16
  ? &(x87_fsw: 101) => uint16
  ? &(x87_fcw: 102) => uint16
  ? &(x87_fop: 103) => uint16
  ? &(x87_ds: 104) => uint16
  ? &(x87_rip: 105) => uint64
  ? &(fpreg_87: 106) => bytes .size 80
  ? &(fpreg_xmm: 107) => bytes .size 256
  ? &(fpreg_ymm: 108) => bytes .size 256
  ? &(lbr_stack: 109) => bytes .size 256
  ? &(lbr_select: 110) => uint64
  ? &(ibs_fetch_ctl: 111) => uint64
  ? &(ibs_fetch_linaddr: 112) => uint64
  ? &(ibs_op_ctl: 113) => uint64
  ? &(ibs_op_rip: 114) => uint64
  ? &(ibs_op_data: 115) => uint64
  ? &(ibs_op_data2: 116) => uint64
  ? &(ibs_op_data3: 117) => uint64
  ? &(ibs_dc_linaddr: 118) => uint64
  ? &(bp_ibstgt_rip: 119) => uint64
  ? &(ic_ibs_extd_ctl: 120) => uint64
)