sevsnp-launch-update-data-map = non-empty<{
  ? &(page-type: 0) => 1..6
  ? &(content: 1) => digest
  ? &(gpa: 2) => uint
  ? &(page-data: 3) => byte .bits sev-snp-page-data
  ? &(vmpl-perms: 4) => uint64
  ? &(seq-no: 5) => uint
}>
